# build:
#   stage: build
#   tags:
#     - vm
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   variables:
#     BUILD_CONTEXT: "."
#   script:
#     - |-
#       # 'Docker login'
#       mkdir -p /kaniko/.docker
#       echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#       echo "CI_REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}"
#       echo "DESTINATION=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}"
#     - |-
#        /kaniko/executor --context "${CI_PROJECT_DIR}/${BUILD_CONTEXT}" \
#                         --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
#                         --cache=true \
#                         --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}"
#   rules: 
#     - if: $CI_COMMIT_BRANCH
#       exists:
#         - Dockerfile 



build:
  stage: build
  script:
    - |-
      echo "Done build!"